pipeline {
    agent any 
    stages {
        stage('Run Unit Tests') {
            steps {
                sh 'bash-calculator/test/bats/bin/bats test/test/test.bats'
            }
        }
    }
}
